[package]
name = "cardano"
version = "0.1.1"
authors = ["Clemens Horn <clemens.horn@mni.thm.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
tokio = { version = "1.9.0", features = ["full"] }
console = "0.14.1"
dialoguer = "0.8.0"
# indicatif = "0.16.2"
# regex = "1.5.4"
# cardano-serialization-lib = "8.0.0"

[dev-dependencies]
assert_cmd = "2.0.0"
predicates = "2.0.1"
