[package]
name = "cardano"
version = "0.1.1"
authors = ["Clemens Horn <clemens.horn@mni.thm.de>"]
edition = "2018"
license = "MIT"
description = "CLI for managing cardano components"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
tokio = { version = "1.9.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.66"
console = "0.14.1"
dialoguer = "0.8.0"
anyhow = "1.0.42"
ctrlc = "3.2.0"
human-panic = "1.0.3"
# indicatif = "0.16.2"
# regex = "1.5.4"
# cardano-serialization-lib = "8.0.0"

[dev-dependencies]
assert_cmd = "2.0.0"
predicates = "2.0.1"
serde_test = "1.0.127"
pretty_assertions = "0.7.2"