[package]
name = "cardano"
version = "0.1.1"
authors = ["Clemens Horn <clemens.horn@mni.thm.de>"]
edition = "2018"
build = "build.rs"
links = "libsodium"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
tokio = { version = "1.9.0", features = ["full"] }
console = "0.14.1"
# indicatif = "0.16.2"
# dialoguer = "0.8.0"
# regex = "1.5.4"
# cardano-serialization-lib = "8.0.0"

[build-dependencies]
autotools = "0.2.3"
pkg-config = "0.3.19"

[features]
libsodium-sys = []