name: Cardano CLI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Cardano CLI 
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --release --all-features
  
  format:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format build
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
            override: true
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.TOKEN}}

  check:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        uses: actions-rs/cargo@v1.0.1
        with:
          command: check

  test:
    needs:
      - check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions-rs/cargo@v1.0.1
        with: 
          command: test
          args: --verbose --all-features
